// export const employees = [
//     {
//       id: 1,
//       empID: "009120",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 2,
//       empID: "009121",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: false,
//     },
//     {
//       id: 3,
//       empID: "009122",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 4,
//       empID: "009123",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 5,
//       empID: "009124",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 6,
//       empID: "009125",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 7,
//       empID: "009126",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 8,
//       empID: "009127",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 9,
//       empID: "009128",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 10,
//       empID: "009129",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 11,
//       empID: "009130",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 12,
//       empID: "009131",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 13,
//       empID: "009132",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 14,
//       empID: "009133",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 15,
//       empID: "009134",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 16,
//       empID: "009135",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 17,
//       empID: "009136",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 18,
//       empID: "009137",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 19,
//       empID: "009138",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//     {
//       id: 20,
//       empID: "009139",
//       name: "Ajayi Esther",
//       department: "Marketing",
//       role: "Manager",
//       email: "esther@sbc.org",
//       empType: "Contract",
//       active: true,
//     },
//   ];